### ISSUE TITLE
Add CD for docs project

### ISSUE THREAD

**Issue by solomondefi-dev** [SolomonDefi/solomon-monorepo#13]
Upload to Github pages when a commit that starts with `:bookmark: [docs]:` is detected.

- For restricting actions based on commit message, a variation on the method described here should work: https://www.eliostruyf.com/devhack-skip-github-actions-specific-commits-messages/
- Only on main branch, e.g.
```yaml
on:
  push:
    branches: 
      - develop
jobs:
  main:
    name: Deploy docs
```
- Deploy with https://github.com/JamesIves/github-pages-deploy-action
  -  Alternative (they probably both work fine): https://github.com/peaceiris/actions-gh-pages
- Build with `pnpx nx build developer-docs`
  - Vitepress output dir may need to by configured?
